name: Dlpu Auto Sign In

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sign_in:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade requests
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 'Sign In'
      env:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        location: ${{ secrets.location }} 
      run: |
        python sign_in.py
        python notification.py
